import prisma from '../src/lib/prisma'
import { Prisma } from '../src/generated/prisma/client'

type SeedData = {
  users: Prisma.UserCreateManyInput[]
  categories: Prisma.CategoryCreateManyInput[]
  addresses: Prisma.AddressCreateManyInput[]
  products: Prisma.ProductCreateManyInput[]
  productImages: Prisma.ProductImageCreateManyInput[]
  carts: Prisma.CartCreateManyInput[]
  cartItems: Prisma.CartItemCreateManyInput[]
  orders: Prisma.OrderCreateManyInput[]
  orderItems: Prisma.OrderItemCreateManyInput[]
  payments: Prisma.PaymentCreateManyInput[]
  processedStripeEvents: Prisma.ProcessedStripeEventCreateManyInput[]
}

// seed-data.json is generated by `npm run db:snapshot` — run it before restoring
// eslint-disable-next-line @typescript-eslint/no-require-imports
const seedData = require('./seed-data.json') as SeedData

async function main() {
  console.log('🌱 Iniciando restauração do banco...\n')

  await prisma.$transaction(async (tx) => {
    // DELETE — filhos primeiro, pais depois
    console.log('🗑️  Limpando tabelas...')

    await tx.payment.deleteMany()
    console.log('  payments: limpo')

    await tx.orderItem.deleteMany()
    console.log('  order_items: limpo')

    await tx.order.deleteMany()
    console.log('  orders: limpo')

    await tx.cartItem.deleteMany()
    console.log('  cart_items: limpo')

    await tx.cart.deleteMany()
    console.log('  carts: limpo')

    await tx.productImage.deleteMany()
    console.log('  product_images: limpo')

    await tx.address.deleteMany()
    console.log('  addresses: limpo')

    await tx.product.deleteMany()
    console.log('  products: limpo')

    await tx.category.deleteMany()
    console.log('  categories: limpo')

    await tx.user.deleteMany()
    console.log('  users: limpo')

    await tx.processedStripeEvent.deleteMany()
    console.log('  processed_stripe_events: limpo')

    console.log('\n📥 Restaurando dados...')

    // CREATE — pais primeiro, filhos depois
    if (seedData.users.length > 0) {
      await tx.user.createMany({ data: seedData.users })
      console.log(`  users: ${seedData.users.length} registro(s) restaurado(s)`)
    }

    if (seedData.categories.length > 0) {
      await tx.category.createMany({ data: seedData.categories })
      console.log(`  categories: ${seedData.categories.length} registro(s) restaurado(s)`)
    }

    if (seedData.addresses.length > 0) {
      await tx.address.createMany({ data: seedData.addresses })
      console.log(`  addresses: ${seedData.addresses.length} registro(s) restaurado(s)`)
    }

    if (seedData.products.length > 0) {
      await tx.product.createMany({ data: seedData.products })
      console.log(`  products: ${seedData.products.length} registro(s) restaurado(s)`)
    }

    if (seedData.carts.length > 0) {
      await tx.cart.createMany({ data: seedData.carts })
      console.log(`  carts: ${seedData.carts.length} registro(s) restaurado(s)`)
    }

    if (seedData.productImages.length > 0) {
      await tx.productImage.createMany({ data: seedData.productImages })
      console.log(`  product_images: ${seedData.productImages.length} registro(s) restaurado(s)`)
    }

    if (seedData.cartItems.length > 0) {
      await tx.cartItem.createMany({ data: seedData.cartItems })
      console.log(`  cart_items: ${seedData.cartItems.length} registro(s) restaurado(s)`)
    }

    if (seedData.orders.length > 0) {
      await tx.order.createMany({ data: seedData.orders })
      console.log(`  orders: ${seedData.orders.length} registro(s) restaurado(s)`)
    }

    if (seedData.orderItems.length > 0) {
      await tx.orderItem.createMany({ data: seedData.orderItems })
      console.log(`  order_items: ${seedData.orderItems.length} registro(s) restaurado(s)`)
    }

    if (seedData.payments.length > 0) {
      await tx.payment.createMany({ data: seedData.payments })
      console.log(`  payments: ${seedData.payments.length} registro(s) restaurado(s)`)
    }

    if (seedData.processedStripeEvents.length > 0) {
      await tx.processedStripeEvent.createMany({ data: seedData.processedStripeEvents })
      console.log(`  processed_stripe_events: ${seedData.processedStripeEvents.length} registro(s) restaurado(s)`)
    }
  })

  console.log('\n✅ Restauração concluída com sucesso!')
}

main()
  .catch((err) => {
    console.error('❌ Erro ao restaurar banco:', err)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
